---
# tasks file for roles/nginx

- name: Put nginx.conf on host
  template:
    src: "templates/nginx.conf"
    dest: "/nginx.conf"
    mode: 0644

- name: Run nginx container
  docker_container:
    name: nginx
    image: nginx:stable
    hostname: nginx
    volumes: 
      - /nginx.conf:/etc/nginx/nginx.conf:ro
    published_ports:
        - "9000:80"
    networks:
      - name: web
        links: "{{ servers.keys() | list }}"
    state: started
    restart_policy: always