---
# tasks file for roles/nginx

- name: Put nginx.conf inside
  template:
    src: "templates/nginx.conf"
    dest: "/nginx.conf"
    mode: 0644

- name: Run nginx container
  docker_container:
    name: nginx
    image: nginx:stable
    mounts:
      - source: "/nginx.conf"
        target: "/etc/nginx/nginx.conf"
        type: bind
    hostname: nginx
    published_ports:
        - "9000:80"
    networks:
      - name: "{{ network }}" 
        links: "{{ servers.keys() | list }}"
    state: 'started'
    restart_policy: 'always'