- name: Run web Application and Nginx balancer
  hosts: docker_webservers
 
  vars:
    servers:
      server_1: 2024
      server_2: 2023 
      server_3: 2022
    image_name: dariazhdanovadev/cicd-exam-images
    
    network: web
        
  roles:
    - { role: web, image_tag: "42"}
    - role: nginx