- name: Run web Application and Nginx balancer
  hosts: test
 
  vars:
    servers:
      - server_1: 2024
      - server_2: 2023 
      - server_3: 2022
    network: ansible
        
  roles:
      - role: web
      - role: nginx